### ISSUE TITLE
Class '\Omnipay\PaymentSense\Gateway' not found

### ISSUE THREAD

**Issue by hillelcoren** [coatesap/omnipay-paymentsense#3]
I'm getting the following error after updating to the latest release.

    RuntimeException in GatewayFactory.php line 106:
    Class '\Omnipay\PaymentSense\Gateway' not found

Tracing through the code `Helper::getGatewayClassName($class)` is called which returns `'\Omnipay\PaymentSense\Gateway'`

Sorry if it's user error, I've tried `php artisan optimize` and `composer dump-autoload`

**Comment by coatesap** [comment]
Ah, yes, that's one side effect that we've noticed following the move to make all independently developed drivers use their own namespace.

When using Omnipay's GatewayFactory, you now have to pass in the full namespaced name of the driver, eg `$factory->create('\\Coatesap\\PaymentSense\\Gateway' ...`

It's to do with the way that `Helper::getGatewayClassName()` treats Omnipay namespaced drivers differently - allowing you to drop the namespace, and appending 'Gateway' on where appropriate. I'm not keen on how it behave differently depending on the driver, but I guess it's a legacy that's hard to change now.

Let me know if you still have any difficulties though.

**Comment by hillelcoren** [comment]
Thanks very much for the info!

**Comment by karneaud** [comment]
@hillelcoren having an issue with this using invoice ninja

**Comment by hillelcoren** [comment]
@karneaud do you want to contact us directly or post to our forum, I'm not sure this issue is the best place to help you resolve the problem.

**Comment by karneaud** [comment]
What is the workaround if any for this?

**Comment by hillelcoren** [comment]
You could try including the full class name in the provider field in the gateways table. 

Please contact us elsewhere if you'd like further help.
